services:
  jnm-front:
    container_name: jnm2026-front-container
    build:
      context: .
      dockerfile: Dockerfile
    # Mappe le port 3000 du conteneur
    expose:
      - 3000
    environment:
      - NODE_ENV=production
    # Redémarre automatiquement le conteneur s'il plante ou si le serveur redémarre
    restart: unless-stopped
    # Optionnel : Limite les ressources pour éviter que Node ne mange toute la RAM
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G