import { LineId, MetroLine, MetroNode } from "./types";

export const LINES: Record<LineId, MetroLine> = {
    A: {
        id: "A",
        name: "Ligne Association",
        color: "#ee6aa0",
        nodes: ["AC", "JT", "NG", "PL"],
    },
    B: {
        id: "B",
        name: "Ligne Communication",
        color: "#cb6ce6",
        nodes: ["JP", "MP", "OR", "GH", "LD", "AS"],
    },
    C: {
        id: "C",
        name: "Ligne Logistique",
        color: "#ff3131",
        nodes: ["IB", "SZ", "JA", "TS", "ET", "GC"],
    },
    D: {
        id: "D",
        name: "Ligne Partenariat",
        color: "#38b6ff",
        nodes: ["NG", "PL", "LM", "CT"],
    },
    E: {
        id: "E",
        name: "Ligne Programme",
        color: "#5e17eb",
        nodes: ["LM", "KB", "IQ", "RB", "CG", "SB", "BB", "HA", "YL"],
    },
    F: {
        id: "F",
        name: "Ligne RSE Ecologie",
        color: "#00bf63",
        nodes: ["GF", "KP", "CG"],
    },
    G: {
        id: "G",
        name: "Ligne RSE Prévention",
        color: "#ffd52b",
        nodes: ["ET", "GF"],
    },
    H: {
        id: "H",
        name: "Ligne Gala",
        color: "#ff751f",
        nodes: ["TS", "ET", "GC", "VD", "AS"],
    },
};

export const NODES: MetroNode[] = [
    { id: "AC", label: "Andrew C.", sublabel: "...", x: 5, y: 20, line: "A", imageUrl: "AC.png" },
    { id: "JT", label: "Justine T.", sublabel: "...", x: 20, y: 20, line: "A", imageUrl: "JT.png" },
    { id: "NG", label: "Nathan G.", sublabel: "...", x: 35, y: 10, line: ["A", "D"], isHub: true, imageUrl: "NG.png" },
    { id: "PL", label: "Paul L.", sublabel: "...", x: 50, y: 10, line: ["A", "D"], isHub: true, imageUrl: "PL.png" },
    { id: "JP", label: "Jérémy P.", sublabel: "...", x: 5, y: 65, line: "B", imageUrl: "JP.png" },
    { id: "MP", label: "Mathis P.", sublabel: "...", x: 10, y: 45, line: "B", imageUrl: "MP.png" },
    { id: "OR", label: "Olivia R.", sublabel: "...", x: 20, y: 45, line: "B", imageUrl: "OR.png" },
    { id: "GH", label: "Guillaume H.", sublabel: "...", x: 30, y: 45, line: "B", imageUrl: "GH.png" },
    { id: "LD", label: "Lucie D.", sublabel: "...", x: 40, y: 45, line: "B", imageUrl: "LD.png" },
    { id: "AS", label: "Anaïs S.", sublabel: "...", x: 50, y: 45, line: ["B", "H"], isHub: true, imageUrl: "AS.png" },
    { id: "IB", label: "Ilann B.", sublabel: "...", x: 15, y: 65, line: "C", imageUrl: "IB.png" },
    { id: "SZ", label: "Sellim Z.", sublabel: "...", x: 15, y: 85, line: "C", imageUrl: "SZ.png" },
    { id: "JA", label: "Julie A.", sublabel: "...", x: 25, y: 90, line: "C", imageUrl: "JA.png" },
    { id: "TS", label: "Thomas S.", sublabel: "...", x: 37.5, y: 90, line: ["C", "H"], isHub: true, imageUrl: "TS.png" },
    { id: "ET", label: "Eliott T.", sublabel: "...", x: 50, y: 90, line: ["C", "G", "H"], isHub: true, imageUrl: "ET.png" },
    { id: "GC", label: "Géraldine C.", sublabel: "...", x: 50, y: 75, line: ["C", "H"], isHub: true },
    { id: "LM", label: "Lina M.", sublabel: "...", x: 65, y: 10, line: ["D", "E"], isHub: true, imageUrl: "LM.png" },
    { id: "CT", label: "Cédric T.", sublabel: "...", x: 75, y: 10, line: "D" },
    { id: "KB", label: "Katia B.", sublabel: "...", x: 65, y: 22.5, line: "E", imageUrl: "KB.png" },
    { id: "IQ", label: "Imane Q.", sublabel: "...", x: 65, y: 35, line: "E" },
    { id: "RB", label: "Romain B.", sublabel: "...", x: 65, y: 47.5, line: "E", imageUrl: "RB.png" },
    { id: "CG", label: "Cyril G.", sublabel: "...", x: 65, y: 60, line: ["E", "F"], isHub: true, imageUrl: "CG.png" },
    { id: "SB", label: "Salma B.", sublabel: "...", x: 72.5, y: 70, line: "E" },
    { id: "BB", label: "Bogdan B.", sublabel: "...", x: 80, y: 70, line: "E", imageUrl: "BB.png" },
    { id: "HA", label: "Halima A.", sublabel: "...", x: 87.5, y: 70, line: "E", imageUrl: "HA.png" },
    { id: "YL", label: "Yann L.", sublabel: "...", x: 95, y: 60, line: "E" },
    { id: "GF", label: "Guillaume F.", sublabel: "...", x: 65, y: 90, line: ["F", "G"], isHub: true },
    { id: "KP", label: "Karen P.", sublabel: "...", x: 65, y: 75, line: "F" },
    { id: "VD", label: "Valentin D.", sublabel: "...", x: 50, y: 60, line: "H", imageUrl: "VD.png" },
];