import { LineId, MetroLine, MetroNode } from "./types";

export const LINES: Record<LineId, MetroLine> = {
    A: {
        id: "A",
        name: "Association",
        color: "#ee6aa0",
        nodes: ["AC", "JT", "NG", "PL"],
    },
    B: {
        id: "B",
        name: "Communication",
        color: "#cb6ce6",
        nodes: ["JP", "MP", "OR", "GH", "LD", "AS"],
    },
    C: {
        id: "C",
        name: "Logistique",
        color: "#ff3131",
        nodes: ["IB", "SZ", "JA", "TS", "ET", "GC"],
    },
    D: {
        id: "D",
        name: "Partenariat",
        color: "#38b6ff",
        nodes: ["NG", "PL", "LM", "CT"],
    },
    E: {
        id: "E",
        name: "Programme",
        color: "#5e17eb",
        nodes: ["LM", "KB", "IQ", "RB", "CG", "SB", "BB", "HA", "YL"],
    },
    F: {
        id: "F",
        name: "RSE Ecologie",
        color: "#00bf63",
        nodes: ["GF", "KP", "CG"],
    },
    G: {
        id: "G",
        name: "RSE Prévention",
        color: "#ffd52b",
        nodes: ["ET", "GF"],
    },
    H: {
        id: "H",
        name: "Gala",
        color: "#ff751f",
        nodes: ["TS", "ET", "GC", "VD", "AS"],
    },
};

export const NODES: MetroNode[] = [
    { id: "AC", label: "Andrew C.", shortLabel: "Andrew", sublabel: "Secrétaire Général", x: 10, y: 20, line: "A", imageUrl: "AC.png" },
    { id: "JT", label: "Justine T.", shortLabel: "Justine", sublabel: "Vice-Présidente/Référente Partenariats", x: 25, y: 20, line: "A", imageUrl: "JT.png" },
    { id: "NG", label: "Nathan G.", shortLabel: "Nathan", sublabel: "Trésorier", x: 35, y: 10, line: ["A", "D"], isHub: true, imageUrl: "NG.png" },
    { id: "PL", label: "Paul L.", shortLabel: "Paul", sublabel: "Président", x: 50, y: 10, line: ["A", "D"], isHub: true, imageUrl: "PL.png" },
    { id: "JP", label: "Jérémy P.", shortLabel: "Jérémy", sublabel: "Référent adjoint COM", x: 5, y: 60, line: "B", imageUrl: "JP.png" },
    { id: "MP", label: "Mathis P.", shortLabel: "Mathis", sublabel: "Référent COM", x: 10, y: 45, line: "B", imageUrl: "MP.png" },
    { id: "OR", label: "Olivia R.", shortLabel: "Olivia", x: 20, y: 45, line: "B", imageUrl: "OR.png" },
    { id: "GH", label: "Guillaume H.", shortLabel: "Guillaume", x: 30, y: 45, line: "B", imageUrl: "GH.png" },
    { id: "LD", label: "Lucie D.", shortLabel: "Lucie", x: 40, y: 45, line: "B", imageUrl: "LD.png" },
    { id: "AS", label: "Anaïs S.", shortLabel: "Anaïs", sublabel: "Référente Gala", x: 50, y: 45, line: ["H", "B"], isHub: true, imageUrl: "AS.png" },
    { id: "IB", label: "Ilann B.", shortLabel: "Ilann", sublabel: "Référent Logistique", x: 15, y: 70, line: "C", imageUrl: "IB.png" },
    { id: "SZ", label: "Sellim Z.", shortLabel: "Sellim", x: 15, y: 85, line: "C", imageUrl: "SZ.png" },
    { id: "JA", label: "Julie A.", shortLabel: "Julie", x: 25, y: 90, line: "C", imageUrl: "JA.png" },
    { id: "TS", label: "Thomas S.", shortLabel: "Thomas", x: 37.5, y: 90, line: ["C", "H"], isHub: true, imageUrl: "TS.png" },
    { id: "ET", label: "Eliott T.", shortLabel: "Eliott", x: 50, y: 90, line: ["C", "G", "H"], isHub: true, imageUrl: "ET.png" },
    { id: "GC", label: "Géraldine C.", shortLabel: "Géraldine", x: 50, y: 75, line: ["C", "H"], isHub: true },
    { id: "LM", label: "Lina M.", shortLabel: "Lina", x: 65, y: 10, line: ["D", "E"], isHub: true, imageUrl: "LM.png" },
    { id: "CT", label: "Cédric T.", shortLabel: "Cédric", x: 80, y: 10, line: "D" },
    { id: "KB", label: "Katia B.", shortLabel: "Katia", sublabel: "Référente Programme", x: 65, y: 22.5, line: "E", imageUrl: "KB.png" },
    { id: "IQ", label: "Imane Q.", shortLabel: "Imane", x: 65, y: 35, line: "E" },
    { id: "RB", label: "Romain B.", shortLabel: "Romain", x: 65, y: 47.5, line: "E", imageUrl: "RB.png" },
    { id: "CG", label: "Cyril G.", shortLabel: "Cyril", x: 65, y: 60, line: ["E", "F"], isHub: true, imageUrl: "CG.png" },
    { id: "SB", label: "Salma B.", shortLabel: "Salma", x: 75, y: 70, line: "E" },
    { id: "BB", label: "Bogdan B.", shortLabel: "Bogdan", x: 85, y: 70, line: "E", imageUrl: "BB.png" },
    { id: "HA", label: "Halima A.", shortLabel: "Halima", x: 95, y: 70, line: "E", imageUrl: "HA.png" },
    { id: "YL", label: "Yann L.", shortLabel: "Yann", x: 95, y: 50, line: "E" },
    { id: "GF", label: "Guillaume F.", shortLabel: "Guillaume", x: 65, y: 90, line: ["F", "G"], isHub: true },
    { id: "KP", label: "Karen P.", shortLabel: "Karen", x: 65, y: 75, line: "F" },
    { id: "VD", label: "Valentin D.", shortLabel: "Valentin", x: 50, y: 60, line: "H", imageUrl: "VD.png" },
];